<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_johndoegmail.com_fad fa-trash text-white</name>
   <tag></tag>
   <elementGuidId>90d9c85b-57db-44cb-a652-b9697105fbd6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='example']/tbody/tr/td[5]/button[2]/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fad.fa-trash.text-white</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot; &quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>b23804b8-e8cb-470d-acf3-ddad9d3fc2bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fad fa-trash text-white</value>
      <webElementGuid>d3d23c6f-edc3-44cf-8cb1-99a1adc7d1f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;example&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;d-flex align-items-center gap-2&quot;]/button[@class=&quot;btn btn-danger&quot;]/i[@class=&quot;fad fa-trash text-white&quot;]</value>
      <webElementGuid>d948041b-4000-4cce-a9f4-1c588197dd4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='example']/tbody/tr/td[5]/button[2]/i</value>
      <webElementGuid>780ebf28-4689-4962-a2a3-0a094e28b5c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/i</value>
      <webElementGuid>945ecb95-3b09-418c-8a28-b0d7667e90b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
