<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Fresh From the Writter_img-fluid rounde_cc60c8</name>
   <tag></tag>
   <elementGuidId>7893f48d-3052-42f9-8146-9d6431b2c1cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'http://localhost:8000/storage/book_covers/1735573587.webp')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.img-fluid.rounded-4.shadow-sm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.img-fluid >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a35389af-3cf2-4593-8c7c-11c4852d6250</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://localhost:8000/storage/book_covers/1735573587.webp</value>
      <webElementGuid>8c2a2ad7-5ad5-46e3-a989-cf95ddbdfebb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-fluid rounded-4 shadow-sm</value>
      <webElementGuid>30741e0b-bbaf-4bd3-a3dd-7145ecbdaac8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>70bf1620-19c0-41aa-812a-479c0e3f8563</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-target</name>
      <type>Main</type>
      <value>#bookDetailModal7894563214785</value>
      <webElementGuid>dee3fa2d-acbc-445d-a760-558f44295b14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;modal-open&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 ms-sm-auto px-md-4 pt-4 discovery&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-3 mb-4 d-flex justify-content-center&quot;]/img[@class=&quot;img-fluid rounded-4 shadow-sm&quot;]</value>
      <webElementGuid>4b298953-2943-4afa-9699-c32dac062453</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'http://localhost:8000/storage/book_covers/1735573587.webp')]</value>
      <webElementGuid>6bc37257-12d9-44f2-8b28-580091d1ccfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>fb4341cc-8bb1-44e7-9d57-47524935420e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'http://localhost:8000/storage/book_covers/1735573587.webp']</value>
      <webElementGuid>2acfd825-fbf1-484b-ae7d-b27ad373dd90</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
