<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Category_category_name</name>
   <tag></tag>
   <elementGuidId>6ca57474-89dd-46d7-b0df-0a9324c39fbd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='category_name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;category_name&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;🪄 Create new category....&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>58d50d3d-2db8-45e8-a552-2d98ec39bcd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f881537e-21a8-4c34-a950-9434bf74ce15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>category_name</value>
      <webElementGuid>18f8823b-ea4e-44a2-9699-aabfc1e10748</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>🪄 Create new category....</value>
      <webElementGuid>19f90103-bd31-407c-a113-6b4d04c7fd26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-9 ms-sm-auto col-lg-10 px-md-4 pt-4 discovery&quot;]/div[@class=&quot;justify-content-between flex-wrap flex-md-nowrap align-items-center pt-4 pb-2 mb-3 border-bottom&quot;]/form[@class=&quot;my-4&quot;]/div[@class=&quot;search w-50&quot;]/div[@class=&quot;search-2&quot;]/input[1]</value>
      <webElementGuid>7af6c0ac-1056-4f0b-827a-49ed9d70e3a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='category_name']</value>
      <webElementGuid>609e649f-5b59-4cac-b5a1-ad696e5636cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>1d58a234-ecd0-4fb5-ad8f-55a8979cc7b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'category_name' and @placeholder = '🪄 Create new category....']</value>
      <webElementGuid>87fb7475-0fe3-48b9-93cb-b9d6f8f82a99</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
