<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__member_email</name>
   <tag></tag>
   <elementGuidId>a2f35fbc-ba4e-4635-88a7-354bcf538924</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='member_email']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;member_email&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;member_email&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>06c744f4-b383-43a9-a5d5-51d8170a7563</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>60106a74-a1da-4ead-96ea-59c2ba443673</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>member_email</value>
      <webElementGuid>2a6ec9ea-3ae6-4c2a-bee5-2f5788f9ab9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control mt-2</value>
      <webElementGuid>2cc291e4-f301-4cd0-8b54-7a2f73d6f40f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;createMemberModal&quot;)/div[@class=&quot;modal-dialog modal-dialog-centered&quot;]/div[@class=&quot;modal-content&quot;]/form[@class=&quot;my-4&quot;]/div[@class=&quot;modal-body px-5&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 mb-4&quot;]/input[@class=&quot;form-control mt-2&quot;]</value>
      <webElementGuid>ce1d3b1d-9792-4255-bb34-bb05f8442299</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='member_email']</value>
      <webElementGuid>f9c87942-2f18-4df0-a932-8e6bc0c3a08e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='createMemberModal']/div/div/form/div[2]/div/div[3]/input</value>
      <webElementGuid>e49e6b43-d060-4536-bcd6-224c0aa0ba33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>f919b2a2-fd9f-4528-9205-c117feea0f2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'member_email']</value>
      <webElementGuid>aa0b2877-80ba-45c7-af1e-3999b239ac09</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
