<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__book_isbn</name>
   <tag></tag>
   <elementGuidId>03892557-4701-4119-9350-67ea8b99a687</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='book_isbn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;book_isbn&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=spinbutton</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>392ca4d6-e63c-4b24-89e6-b2bf0103fce0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>b1e80875-2688-438a-a020-12a5ba613452</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>book_isbn</value>
      <webElementGuid>45a71062-d2aa-48d8-b4e0-153e9dcd4e48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control mt-2</value>
      <webElementGuid>e02ec5a5-2b69-4f27-ad75-450d97d63292</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;createBookModal&quot;)/div[@class=&quot;modal-dialog modal-dialog-centered modal-lg&quot;]/div[@class=&quot;modal-content&quot;]/form[@class=&quot;my-4&quot;]/div[@class=&quot;modal-body px-5&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 col-md-6 mb-4&quot;]/input[@class=&quot;form-control mt-2&quot;]</value>
      <webElementGuid>0774138b-9aee-4da6-acee-b1c8250124e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='book_isbn']</value>
      <webElementGuid>f90fa7f6-4f21-400e-93d6-d9073a17164b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='createBookModal']/div/div/form/div[2]/div/div/input</value>
      <webElementGuid>907aa0d0-bf03-4245-ab4e-3015b75b47df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>e1416313-15c6-43a4-803c-27bc33203afa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'book_isbn']</value>
      <webElementGuid>28db34f6-f36c-423b-9324-3778edd792e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
