<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__book_title</name>
   <tag></tag>
   <elementGuidId>e489a474-22f3-4474-bfb8-2eec2a5007d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='book_title'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.modal-content.p-4 > div.modal-body > div.row > div.col-12.col-md-6.mb-4 > input[name=&quot;book_title&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=dialog[name=&quot;Edit Book Data&quot;i] >> input[name=&quot;book_title&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7671f386-b2e7-4440-a0d8-ce78c913809c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ad94eeb7-d23d-42b1-ac1c-bc5cd9b46608</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>book_title</value>
      <webElementGuid>c82134f7-21a2-4a18-bd84-51290c2166d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>13</value>
      <webElementGuid>fedf82ec-7c09-4b31-bb73-0cdfc3268eed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>13</value>
      <webElementGuid>6c70d3a6-1aba-42b1-b8ec-395ffb098951</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control mt-2</value>
      <webElementGuid>6c2d0150-f3e5-44f2-ad77-630fbb3c5c85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;editModal9517532587456&quot;)/div[@class=&quot;modal-dialog modal-dialog-centered modal-lg&quot;]/div[@class=&quot;modal-content p-4&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 col-md-6 mb-4&quot;]/input[@class=&quot;form-control mt-2&quot;]</value>
      <webElementGuid>4494511d-cb6c-4221-8438-6a532a27e737</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>My Book Cover</value>
      <webElementGuid>ef583bc3-45bd-4638-b2d2-8dea933cf2f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='book_title'])[2]</value>
      <webElementGuid>13a72026-3c77-4caa-a07a-be2496f93f6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='editModal9517532587456']/div/div/div[2]/div/div[2]/input</value>
      <webElementGuid>362b9815-d5b0-40dc-8b8d-e239f97d40ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div[2]/input</value>
      <webElementGuid>4c5e301d-0f37-43b4-a490-e73bdd11a92d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'book_title']</value>
      <webElementGuid>aaa7721f-d47f-4a47-93a8-ee653b22500d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='book_title']</value>
      <webElementGuid>ffc741a5-db41-4154-b89d-40d010c55014</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='createBookModal']/div/div/form/div[2]/div/div[2]/input</value>
      <webElementGuid>67197613-91bf-4072-b3d6-c07435bc2665</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>492527a9-9421-4f76-b704-66261a5342f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
