<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Choose Category.                    _7a419c</name>
   <tag></tag>
   <elementGuidId>c94c3505-60a0-42ed-92c7-76647ffe57f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='exampleSelect']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#exampleSelect</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Create New Book&quot;i >> internal:label=&quot;Pilih Dana&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>28041b7a-16f1-41b6-8f9a-8b1b2999482c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>book_category</value>
      <webElementGuid>b6386a00-99ca-4b28-b07a-8795cb038926</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select mt-2</value>
      <webElementGuid>8c043e15-8512-4e8f-a8fb-4bacd0c4bfae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>exampleSelect</value>
      <webElementGuid>44c3adc1-76cd-4bcb-9240-11e96c3fd75a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Pilih Dana</value>
      <webElementGuid>8b6f8679-4805-4d99-868a-d14f91a2f392</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                        Choose Category...
                                                                                    fiction
                                                                                    anime
                                                                                    thriller
                                                                                    action
                                                                            </value>
      <webElementGuid>22f2554c-309a-446d-9509-8323efd02196</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;createBookModal&quot;)/div[@class=&quot;modal-dialog modal-dialog-centered modal-lg&quot;]/div[@class=&quot;modal-content&quot;]/form[@class=&quot;my-4&quot;]/div[@class=&quot;modal-body px-5&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 col-md-6 mb-4&quot;]/select[@id=&quot;exampleSelect&quot;]</value>
      <webElementGuid>2e057fb8-48d5-4d8d-8044-7dca09fb311e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='exampleSelect']</value>
      <webElementGuid>0d70aaf1-6ae0-4a50-a86f-62d569714a0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='createBookModal']/div/div/form/div[2]/div/div[6]/select</value>
      <webElementGuid>f5ea4595-cc2f-45bd-a27e-75565927a08a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/following::select[1]</value>
      <webElementGuid>842f0435-36a2-4471-a8e3-4dbc487edec6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[7]/preceding::select[1]</value>
      <webElementGuid>d879ba25-c600-4c7a-b792-e423d02bf8ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>42f91293-5b7a-4974-8673-a3cae5793c55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'book_category' and @id = 'exampleSelect' and (text() = '
                                        Choose Category...
                                                                                    fiction
                                                                                    anime
                                                                                    thriller
                                                                                    action
                                                                            ' or . = '
                                        Choose Category...
                                                                                    fiction
                                                                                    anime
                                                                                    thriller
                                                                                    action
                                                                            ')]</value>
      <webElementGuid>b60cec48-7250-49f7-9c94-011dbd83b927</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
